# Generated by Django 4.2.13 on 2024-05-30 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='category/default.jpg', upload_to='category/'),
        ),
    ]
